---
sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
matrix:
  include:
    - rvm: 2.7
      os: osx
before_script:
- bundle install
- rake compile
script: rspec
